services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: diet_user
      POSTGRES_PASSWORD: diet_password
      POSTGRES_DB: diet_planner
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    ports:
      - "8080:8000"
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://diet_user:diet_password@db:5432/diet_planner
    depends_on:
      - db
