openapi: 3.0.0
info:
  title: AI-Driven Meal Planner API
  description: API for the AI-Driven Meal Planner project
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /api/user/:
    post:
      summary: Authenticate a user and return a token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
  /api/meals/:
    post:
      summary: Add a meal to the user's meal list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                ingredients:
                  type: string
                calories:
                  type: integer
      responses:
        "200":
          description: Meal added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  meal:
                    type: object
  /api/meal-plans/:
    post:
      summary: Create a new meal plan for the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                mealPlan:
                  type: array
                  items:
                    type: object
                    properties:
                      meal:
                        type: string
                      day:
                        type: string
                      time:
                        type: string
      responses:
        "200":
          description: Meal plan created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /api/shopping-list/:
    post:
      summary: Create a shopping list based on the user's meals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      quantity:
                        type: integer
      responses:
        "200":
          description: Shopping list created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /api/nutrition/:
    post:
      summary: Get nutrition details for a given food item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                food:
                  type: string
                quantity:
                  type: integer
      responses:
        "200":
          description: Nutrition details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  nutrition:
                    type: object
                    properties:
                      calories:
                        type: integer
                      protein:
                        type: integer
                      fat:
                        type: integer
                      sugars:
                        type: integer
                      carbs:
                        type: integer
